
- hosts: workers
  become: yes
  become_user: ubuntu
  tasks:
    - name: Gather worker public ip
      amazon.aws.ec2_metadata_facts:
      register: ec2_metadata
    - name: Set public IP address variable
      set_fact:
        public_ip: "{{ ec2_metadata.ansible_ec2_public_ipv4 }}"
    - name: Check if ec2_metadata is defined
      fail:
        msg: "Failed to get EC2 metadata. Check if running on EC2 instance."
      when: ec2_metadata is not defined

    - name: Print public ip 
      debug:
        var: item.ansible_ec2_public_ipv4
      with_items: "{{ec2_metadata}}"

